# Generated by Django 6.0.1 on 2026-01-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('skills', models.CharField(choices=[('medical', '👨\u200d⚕️ Medical Professional'), ('logistics', '🚚 Logistics Support'), ('tech', '💻 Tech Support'), ('counseling', '🧠 Counseling'), ('other', '✨ Other')], max_length=20)),
                ('hours_per_week', models.IntegerField()),
                ('motivation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
